name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚧 Set up project
        run: npm run dev:prepare

      - name: 🛠 Build project
        run: npm run dev:build

      - name: 🧪 Test project
        run: npm run test

      - name: 🟩 Coverage
        uses: codecov/codecov-action@v3
